# Copyright (C) 2019 Intel Corporation.  All rights reserved.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception


#==============================================================================
# Sample Application Configuration - Default
#------------------------------------------------------------------------------
# 
#### Description:
#
#    This configuration provides a typical setup with LOG and printk enabled.
#    The main stack size is increased to 8 KB (could be refined later).
#
#### Note:
#
#    This sample is not optimized for production use — it serves as a proof of
#    concept demonstrating the coexistence of Zephyr, WAMR, and TFLM.
#
CONFIG_PRINTK=y
CONFIG_LOG=y
CONFIG_MAIN_STACK_SIZE=8192
CONFIG_LOG_MODE_IMMEDIATE=y 
CONFIG_POSIX_API=n


#==============================================================================
# WAMR_BUILD_LIBC_WASI - Dependencies 
#------------------------------------------------------------------------------
#
#### Description:
#
#    `WAMR_BUILD_LIBC_WASI` is mainly used on higher-level platforms (Linux,
#    Windows). On Zephyr, enabling this flag requires pulling in both the
#    network and file system stacks along with their dependencies.
#
#    Ideally, a modular RTOS approach would allow selecting only the necessary
#    components, improving size and clarity.
#

# File System Stack
CONFIG_FILE_SYSTEM=y
CONFIG_FILE_SYSTEM_LITTLEFS=y

# Network Stack
CONFIG_NETWORKING=y
CONFIG_NET_IPV4=y
CONFIG_NET_IPV6=y
CONFIG_NET_TCP=y
CONFIG_NET_SOCKETS=y

# File System Stack - Dep
# 
#  LittleFS requires:
#     - CONFIG_FS_LITTLEFS_BLK_DEV 
#     - CONFIG_FS_LITTLEFS_FMP_DEV
# However, enabling CONFIG_FS_LITTLEFS_BLK_DEV together with CONFIG_FLASH
# currently leads to unresolved symbols.
CONFIG_FLASH=y
CONFIG_FLASH_MAP=y

# Network Stack - Dep
CONFIG_TEST_RANDOM_GENERATOR=y       # `sys_rand_get` (unresolved symbol)


#==============================================================================
# TensorFlow Lite Micro - Dependencies
#------------------------------------------------------------------------------
#
#### Description:
#
#    Inspired by Zephyr’s TFLM samples. Some additional dependencies were added
#    due to compilation issues encountered when integrating WAMR.
#
CONFIG_CPP=y
CONFIG_STD_CPP17=y                   # `std::consitional_t`, Type, etc..
CONFIG_REQUIRES_FULL_LIBC=y
CONFIG_TENSORFLOW_LITE_MICRO=y


# Investigate Later:
# CONFIG_TENSORFLOW_LITE_MICRO_CMSIS_NN_KERNELS