#ifndef CONFIG_H
#define CONFIG_H

#if ENABLE_BENCHMARK_ACKERMANN
    #define BENCHMARK_ACKERMANN 1
#else
    #define BENCHMARK_ACKERMANN 0
#endif

#if ENABLE_BENCHMARK_BASE64
    #define BENCHMARK_BASE64 1
#else
    #define BENCHMARK_BASE64 0
#endif

#if ENABLE_BENCHMARK_FIB2
    #define BENCHMARK_FIB2 1
#else
    #define BENCHMARK_FIB2 0
#endif

#if ENABLE_BENCHMARK_GIMLI
    #define BENCHMARK_GIMLI 1
#else
    #define BENCHMARK_GIMLI 0
#endif

#if ENABLE_BENCHMARK_MATRIX
    #define BENCHMARK_MATRIX 1
#else
    #define BENCHMARK_MATRIX 0
#endif

#if ENABLE_BENCHMARK_MEMMOVE
    #define BENCHMARK_MEMMOVE 1
#else
    #define BENCHMARK_MEMMOVE 0
#endif

#if ENABLE_BENCHMARK_RANDOM
    #define BENCHMARK_RANDOM 1
#else
    #define BENCHMARK_RANDOM 0
#endif

#if ENABLE_BENCHMARK_SIEVE
    #define BENCHMARK_SIEVE 1
#else
    #define BENCHMARK_SIEVE 0
#endif

#if ENABLE_BENCHMARK_HEAPSORT
    #define BENCHMARK_HEAPSORT 1
#else
    #define BENCHMARK_HEAPSORT 0
#endif

#if ENABLE_BENCHMARK_NESTEDLOOP
    #define BENCHMARK_NESTEDLOOP 1
#else
    #define BENCHMARK_NESTEDLOOP 0
#endif

#if ENABLE_BENCHMARK_DUMMY
    #define BENCHMARK_DUMMY 1
#else
    #define BENCHMARK_DUMMY 0
#endif

#if ENABLE_BENCHMARK_SOCKET_CREATE
    #define BENCHMARK_SOCKET_CREATE 1
#else
    #define BENCHMARK_SOCKET_CREATE 0
#endif

#if ENABLE_BENCHMARK_SOCKET_CONNECT
    #define BENCHMARK_SOCKET_CONNECT 1
#else
    #define BENCHMARK_SOCKET_CONNECT 0
#endif

#if ENABLE_BENCHMARK_SOCKET_BIND
    #define BENCHMARK_SOCKET_BIND 1
#else
    #define BENCHMARK_SOCKET_BIND 0
#endif

#if ENABLE_BENCHMARK_SOCKET_SENDTO
    #define BENCHMARK_SOCKET_SENDTO 1
#else
    #define BENCHMARK_SOCKET_SENDTO 0
#endif

#if ENABLE_BENCHMARK_SOCKET_RECVFROM
    #define BENCHMARK_SOCKET_RECVFROM 1
#else
    #define BENCHMARK_SOCKET_RECVFROM 0
#endif

#if ENABLE_BENCHMARK_FS_FOPEN
    #define BENCHMARK_FS_FOPEN 1
#else
    #define BENCHMARK_FS_FOPEN 0
#endif

#if ENABLE_BENCHMARK_FS_FWRITE
    #define BENCHMARK_FS_FWRITE 1
#else
    #define BENCHMARK_FS_FWRITE 0
#endif

#if ENABLE_BENCHMARK_FS_FREAD
    #define BENCHMARK_FS_FREAD 1
#else
    #define BENCHMARK_FS_FREAD 0
#endif

#if ENABLE_BENCHMARK_FS_FSEEK
    #define BENCHMARK_FS_FSEEK 1
#else
    #define BENCHMARK_FS_FSEEK 0
#endif

#if ENABLE_BENCHMARK_FS_FCLOSE
    #define BENCHMARK_FS_FCLOSE 1
#else
    #define BENCHMARK_FS_FCLOSE 0
#endif

#if ENABLE_BENCHMARK_FS_UNLINK
    #define BENCHMARK_FS_UNLINK 1
#else
    #define BENCHMARK_FS_UNLINK 0
#endif

#if ENABLE_BENCHMARK_FS_MKDIR
    #define BENCHMARK_FS_MKDIR 1
#else
    #define BENCHMARK_FS_MKDIR 0
#endif

#if ENABLE_BENCHMARK_FS_RENAME
    #define BENCHMARK_FS_RENAME 1
#else
    #define BENCHMARK_FS_RENAME 0
#endif

#if ENABLE_BENCHMARK_FS_PERF
    #define BENCHMARK_FS_PERF 1
#else
    #define BENCHMARK_FS_PERF 0
#endif

#endif /* CONFIG_H */